name: Build and Push docker Image 

on:
    push:
        branches:
            - main 
jobs: 
    # docker build workflow 
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code 
              uses: actions/checkout@v3

            # - name: Set up QEMU 
            #   uses: docker/setup-qemu-action@v2

            # Setup and install docker 
            - name: Docker Setup
              uses: docker/setup-buildx-action@v2
            
            # Login to docker 
            - name: Docker Registry Login
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{secrets.CONTAINER_REGISTRY_TOKEN }}
            
